- name: brew cask install packages
  homebrew_cask: name="{{ item }}" state=present
  with_items: "{{homebrew_cask_packages}}"

- name: update cask packages
  shell: for c in `brew list --cask`; do ! brew info --cask $c | grep -qF "Not installed" || brew install --cask $c; done
  become: yes
