- name: Tap a hashicorp Homebrew repository, state present
  community.general.homebrew_tap:
  name: hashicorp/tap

- name: install terraform
  community.general.homebrew:
    name: terraform
    state: present

- name: copy terraform setting to .oh-my-zsh/custom
  copy: src=terraform.zsh dest=~/.oh-my-zsh/custom/ mode=0644