- name: Tap a hashicorp Homebrew repository, state present
  community.general.homebrew_tap:
    name: hashicorp/tap

- name: brew update & upgrade all
  homebrew: update_homebrew=yes upgrade_all=yes

- name: install packages
  homebrew: name="{{ item.name }}" state="{{ item.state|default("latest") }}" install_options="{{ item.install_options|default() }}"
  with_items: "{{homebrew_packages}}"