- name: install tmux
  community.general.homebrew:
    name: tmux
    state: present

- name: copy .tmux.conf
  copy: src=.tmux.conf dest=~/.tmux.conf mode=0644

- name: Install tmux plugin manager
  git: repo=https://github.com/tmux-plugins/tpm dest=~/.tmux/plugins/tpm

- name: copy tmux-pbcopy
  copy: src=tmux-pbcopy dest=/usr/local/bin mode=0755

- name: copy scripts
  copy: src="{{item}}" dest=~/tools/ mode=0755
  with_items: "{{scripts}}"