- name: install peco
  community.general.homebrew:
    name: peco
    state: present

- name: create .peco directory
  file: path=~/.peco state=directory mode=0755

- name: copy config.json
  copy: src=config.json dest=~/.peco/config.json mode=0644

- name: copy zsh setting
  copy: src=peco.zsh dest=~/.oh-my-zsh/custom/peco.zsh mode=0644
